### ISSUE TITLE
Bullet 2.86 release

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-html5-tools#12]
https://github.com/bulletphysics/bullet3/releases

**Comment by xpenatan** [comment]
Hi, Yes I know there is 2.86. I stay with same libgdx bullet source code version (which does some patch). Didn't check yet if they updated it.

**Comment by nicolaichuk** [comment]
I done PR https://github.com/libgdx/libgdx/pull/4636
@xpenatan, please review.

**Comment by xpenatan** [comment]
Xoppa is usually the one who update bullet. You may ask him to analyse or to update. You can easily find him in IRC channel.  Tiny changes to libgdx takes some months to merge. With a big commit It could take years     ( jking ^^ but its close haha).  Is there really a need to update ?  From what I see its more VR stuff.

**Comment by nicolaichuk** [comment]
@xpenatan

> With a big commit It could take years

These commit can not be made small. I believe that I am doing a useful job in the development of the project. While I'm ready to spend my time to change this PR, if maintainers spend their time to review this PR. Let's see what will happen next. If you can somehow help, I'll be grateful.

> jking ^^ but its close haha

Sorry, I did not understand what you're talking about.

**Comment by xpenatan** [comment]
> These commit can not be made small.

Yes I know its impossible to do small commit with this.  I know libgdx since 2012 and I know that with few lines fix takes days/months for them to analyse and accept the changes.  With a big patch lets just hope it pass faster ! 

> I do not have a lot of experience using the IRC. What kind of channel is it? If you use IRC often, can you please ask him to review this PR?

Its a chat channel.  You can connect with https://hexchat.github.io/ (or other free clients) or via web https://webchat.freenode.net/ (channel: #libgdx)

Which bullet feature do you need ?
