### ISSUE TITLE
getPreloader().loadAsset

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-html5-tools#15]
we need write many "copy-past" assets paths In method createApplicationListener() in DragomeApplication class 

for example https://github.com/xpenatan/gdx-shadertoy/blob/master/dragome/src/com/xoppa/dragome/launcher/ShaderToyLauncher.java

Can it set loadAsset from path mask?

For example as "shaders/*.glsl", etc.

**Comment by xpenatan** [comment]
We can do like gwt backend which generates a file that contains all assets path. 

@fpetrola  is it possible by code to loop and get names of all files that has not been downloaded yet in root/assets path?

**Comment by fpetrola** [comment]
server side or client side?

**Comment by nicolaichuk** [comment]
If I understand @xpenatan 

Client ask server list all assets path, then select paths by masks list and than call loadAsset for paths that valid mask.

**Comment by fpetrola** [comment]
We could create a service for assets listing, and then use the already implemented mechanism to load each selected asset.

**Comment by fpetrola** [comment]
Listing assets service could list resources from classpath as weel as file system assets.

**Comment by xpenatan** [comment]
in gwt backend a  ".txt" file is created with all assets that copied from android/assets and when client starts it download that file first to know the paths of other assets.  This is simple to do and the code is mostly done because its already ported from gwt (just need to test). Knowing all files we can filter which to download first (or all) and later.
